### ISSUE TITLE
Question: Is STA+AP concurrent mode supported in mt7612u ?

### ISSUE THREAD

**Issue by jimyang2008** [morrownr/7612u#2]
Here's what I have tried

```
# add wlan1
sudo iw phy phy0 interface add wlan1 type managed
# change MAC to be different from wlan0
sudo ip link set wlan1 address <different_MAC_from_wlan0>
# try to setup AP on wlan0 and STA on wlan1
sudo hostapd -i wlan0 /etc/hostapd/hostapd-5g.conf
sudo wpa_supplicant -i wlan1 -c /etc/wpa_supplicant/wpa_supplicant-wlan1.conf
```

The observations are
* To connect to AP on wlan0, the password has to be provided again at the first or second time although it is correct all the time.
* STA cannot connect
* AP failed to accept client connection
* wifi device access get no response

**Comment by morrownr** [comment]
The short answer is yes.

It has been some time since I tried this so my memory is not fresh and I am currently in the process of moving with most equipment is packed so my ability to check things out is limited.

With that said, here is the relevant statement from $ iw list

#{ IBSS } <= 1, #{ managed, AP, mesh point, P2P-client, P2P-GO } <= 2,
  total <= 2, #channels <= 1, STA/AP BI must match

Make sure both are on the same channel as I think that is the problem I have seen people run into.

Cheers

**Comment by morrownr** [comment]
Is this issue solved?
